### ISSUE TITLE
Cygwin sudo error (admin mode)

### ISSUE THREAD

**Issue by PVTD** [BobHasNoSoul/JFTool#3]
Using the cygwin terminal with administrator rights (no WSL support for LTSB/C) I used to be able to make changes, I haven't tried it since 10.5.5 but now I'm on 10.6.3 and it gives me an error every time it wants to save something:

**Please enter your choice: 10
what is the current name of your server
(this appears in the top of your browser window as a page title)
this is case-sensitive (Default 'Jellyfin')
Jellyfin
What do you want to call your server?
MYSERVERNAME
One Moment Please
./tool-cygwin.sh: line 300: sudo: command not found
./tool-cygwin.sh: line 301: sudo: command not found
./tool-cygwin.sh: line 302: sudo: command not found
./tool-cygwin.sh: line 303: sudo: command not found**

Thanks for the upkeep of your tool bro, loving it!

**Comment by BobHasNoSoul** [comment]
ahh sorry about this thats just because i left "sudo" in the command line, sorry for the long wait i will get this sorted and fix this issue.
