### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by heyhippari** [BobHasNoSoul/JFTool#5]
Just as an FYI, since you are including files from jellyfin-web (Which are GPLv2), your MIT license is invalid.

You can't re-license these files for your project, they should still be GPLv2-licensed.

**Comment by thornbill** [comment]
You could just specify the correct license for the files from web and keep the overall project license the same.

**Comment by BobHasNoSoul** [comment]
Thank you for your input, i was unaware of the difference in license (because this was a fairly rushed project and didnt pay too much attention when first making this) and have since added the license to the folders that are conflicting hope this fixes the issue.

**Comment by thornbill** [comment]
Thanks for resolving this so quickly!
